### ISSUE TITLE
Auto-publish new gem versions using Github Actions

### ISSUE THREAD

**Issue by czj** [levups/fuel_surcharge#25]
We could automate gem publishing using a Rubygems API token and this Github Action :

https://github.com/scarhand/actions-ruby

Whenever we tag a new release, it can push to Rubygems.

**Comment by bobmaerten** [comment]
Avec la signature de la gem, ça risque d'être plus compliqué :/

**Comment by czj** [comment]
Passons donc outre la signature !

**Comment by bobmaerten** [comment]
J'ai repris un peu le code de l'action en question, et si je comprends bien, ça se déclenche à chaque push, vérifie que le commit est un tag et publie le cas échéant.

Du coup la démarche pour publier est de correctement paramétrer le gemspec, faire un tag et push sur le repo.

Du coup entre ca et faire un `rake release` en local, c'est un peu kif kif. 

Faudrait trouver un workflow plus simple/clair/linéaire/reproductible/toussa.

**Comment by czj** [comment]
Effectivement c’est pas parfait parfait comme workflow.

Pour faire un tag il faut de toute façon une action manuelle, et manuelle au point de saisir le numéro de vision … à moins de détecter dans le gemspec si le numéro de version change, et donc ce cas on peut créer automatiquement le tag lors du merge dans master !

**Comment by bobmaerten** [comment]
On devrait pouvoir arriver à quelque chose comme ce qui est fait dans le Rakefile

```
  latest_release = `git tag --sort=taggerdate | tail -n 1`.strip
  next_release   = "v#{FuelSurcharge::VERSION}"

  config.future_release       = next_release if next_release > latest_release
```

mais dans le workflow de publish ou non.
